Stop if fetching new JSON fails

diff --git a/rankings b/rankings
--- a/rankings
+++ b/rankings
@@ -4,6 +4,11 @@ update_json() {
     local year=$1
     local url="http://adventofcode.com/$year/leaderboard/private/view/$(< boardid).json"
     curl -s -b session="$(< cookie)" "$url" | jq -S '.' > "$year"/leaderboard.json.tmp
+    if [[ ! -s $year/leaderboard.json.tmp ]]; then
+        echo "Could not get new data from adventofcode.com, session cookie expired?" >&2
+        rm "$year"/leaderboard.json.tmp
+        exit 1
+    fi
 
     # Compare to current leaderboard and signal in return status if year has to be built
     if cmp -s "$year"/leaderboard.json "$year"/leaderboard.json.tmp; then
